[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HydroAngleAnalyzer"
version = "0.1.1"
description = "A simple Python library to parse MD trajectories from lammps and ASE and measure the contact through different methods"
authors = [
    {name = "Gabriel", email = "gabriel.taillandier@matgenix.com"},
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    # Add dependencies here, e.g., "numpy>=1.21.0"
]

[project.scripts]
hydro_angle_analyzer = "HydroAngleAnalyzer.module:main"
